apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tc-payment-s4-dep
  namespace: fiap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-tc-payment-s4
  template:
    metadata:
      labels:
        app: app-tc-payment-s4
    spec:
      containers:
        - name: app-tc-payment-s4
          image: 'jcmds/fiap-8soat-tc-s4-payment-gateway:latest'
          ports:
            - name: http 
              containerPort: 80
              protocol: TCP           
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "600m"
              memory: "1Gi"
          env:
            - name: RabbitMQ__HostName
              value: rabbitmq.fiap.svc.cluster.local             
            - name: RabbitMQ__UserName
              value: 'admin'
            - name: RabbitMQ__Password
              value: 'admin'
            - name: ConnectionStrings__MongoDb
              value: 'mongodb://admin:admin@mongodb.fiap.svc.cluster.local:27017'
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%                 
        
        


 