apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-tc-payment-s4-dep
  namespace: fiap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-tc-payment-s4
  template:
    metadata:
      labels:
        app: app-tc-payment-s4
    spec:
      containers:
        - name: app-tc-payment-s4
          image: 'jcmds/fiap-8soat-tc:latest'
          ports:
            - name: http 
              containerPort: 8080
              protocol: TCP           
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: credentials-payment-rds
                  key: host
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: credentials-payment-rds
                  key: username
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  name: credentials-payment-rds
                  key: password
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: postgres
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%                 
        
        


 