name: EKS-Deploy
on:
    workflow_dispatch:  # Configuração para deploy manual
env:
    CLUSTER_NAME: eks-fiap-cluster
          
jobs:
  deploy:
    name: Terraform Deploy
    runs-on: ubuntu-latest
    
    environment:
      name: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Get Session Token
        run: echo aws sts get-session-token 
  
      - name: Update Kube Config
        run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}

      - name: Deploy EKS
        run: |
            kubectl apply -f src/k8s/auth/1-namespace.yaml
            kubectl apply -f src/k8s/auth/2-secrets.yaml
            kubectl apply -f src/k8s/auth/3-deployment.yaml
            kubectl apply -f src/k8s/auth/4-hpa.yaml
            kubectl apply -f src/k8s/auth/5-services.yaml
            
            kubectl apply -f src/k8s/backoffice/1-namespace.yaml
            kubectl apply -f src/k8s/backoffice/2-secrets.yaml
            kubectl apply -f src/k8s/backoffice/3-deployment.yaml
            kubectl apply -f src/k8s/backoffice/4-hpa.yaml
            kubectl apply -f src/k8s/backoffice/5-services.yaml

            kubectl apply -f src/k8s/order/1-namespace.yaml
            kubectl apply -f src/k8s/order/2-secrets.yaml
            kubectl apply -f src/k8s/order/3-deployment.yaml
            kubectl apply -f src/k8s/order/4-hpa.yaml
            kubectl apply -f src/k8s/order/5-services.yaml

            kubectl apply -f src/k8s/payment/1-namespace.yaml
            kubectl apply -f src/k8s/payment/2-secrets.yaml
            kubectl apply -f src/k8s/payment/3-deployment.yaml
            kubectl apply -f src/k8s/payment/4-hpa.yaml
            kubectl apply -f src/k8s/payment/5-services.yaml